# This file is used both by conda-build and by the github action conda-incubator/setup-miniconda@v2
name: pandora
channels:
  - bioconda
  - salilab
  - csb-nijmegen
dependencies:
  - python=3.11
  - muscle=5.1
  - blast=2.10
  - numpy
  - numpy-base
  - pip
  - setuptools
  - joblib
  - pandas
  - python-dateutil
  - biopython
  - ipython
  - urllib3=1.26.19